name: Todo App CDK Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Web app Dependencies
        working-directory: ./frontend
        run: npm ci
  
      - name: build web app
        working-directory: ./frontend
        env:
          NUXT_PUBLIC_API_BASE_URL: ${{ secrets.NUXT_PUBLIC_API_BASE_URL }}
          NUXT_PUBLIC_COGNITO_USER_POOL_ID: ${{ secrets.NUXT_PUBLIC_COGNITO_USER_POOL_ID }}
          NUXT_PUBLIC_COGNITO_CLIENT_ID: ${{ secrets.NUXT_PUBLIC_COGNITO_CLIENT_ID }}
        run: npm run build

      - name: install AWS CDK
        run: sudo npm i -g aws-cdk

      - name: install deployment dependencies
        working-directory: ./aws-backend
        run: npm ci

      - name: cdk synth
        working-directory: ./aws-backend
        run: cdk synth

      - name: cdk deploy
        working-directory: ./aws-backend
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: cdk deploy --all --require-approval never